/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void byteLevelAccess(){
	// Modifying the contents of the address 0x20000200
	uint32_t addr =  0x20000200;
	// Making contents of 0x20000200 OxFF
	asm volatile("MOV R0, %0" : : "r"(addr));	// store the address in a register
	asm volatile("MOV R1, #0xFF");				// Store the value to be added
	asm volatile("STR R1, [R0]");				// Load 0xFF into the address
	// making the 7th bit 1
	asm volatile("LDR R1, [R0]");				// Load the value from the register
	asm volatile("AND R1, R1, 0xFFFFFF7F");			// make 7th bit '1'
	asm volatile("STR R1, [R0]");				// Store the value back in the register
}



int main(void)
{
	byteLevelAccess();
    /* Loop forever */
	for(;;);
}
