/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>

// AHB1 address loc
#define RCC_base_addr (*(uint32_t *)0x40023800)	// base addr
#define AHBI_REG_ADDR (*(uint32_t *)0x40023830)	// 32 bit wide
#define GPIOD_EN 3					// (bit) Shift to bit
#define GPIOA_EN 0					// (bit) Shift to bit

// GPIOD config
// Port Port mode offset 0x00 @ GPIOD base addr
// Port output data offset 0x14 @ GPIOD base addr
#define GPIOD_base_addr (*(uint32_t*)0x40020C00)

#define PORT_MODE_ADDR (*(uint32_t*)0x40020C00)
#define PORT_OUTPUT_DATA_ADDR (*(uint32_t*)0x40020C14)

// GPIOA config
// Port Port mode offset 0x00 @ GPIOA base addr
// Port input data offset 0x10 @ GPIOA base addr
#define GPIOA_base_addr (*(uint32_t *) 0x40020000)

#define GPIOA_PORT_MODE_ADDR (*(uint32_t volatile *) 0x40020000)
#define GPIOA_INPUT_DATA_ADDR (*(uint32_t*) 0x40020010)


void setupGPIOD(){
	// Enable the GPIOD port 12
	AHBI_REG_ADDR |= (1 << GPIOD_EN);
	// Set the port mode for GPIOD pin 12
	PORT_MODE_ADDR = 0x01000000; // as general output
}

void setupGPIOA(){
	// Enable the GPIOA port 0
	AHBI_REG_ADDR |= (1 << GPIOA_EN);
	// set the port to be used as an input
	GPIOA_PORT_MODE_ADDR &= ~(0x00000003);
}

int readPA0(){
	return (GPIOA_INPUT_DATA_ADDR&0x00000001);
}

int main(void)
{
    setupGPIOD();
    setupGPIOA();

    // toggle the led
    PORT_OUTPUT_DATA_ADDR |= (1 << 12);

	for(;;){
		// turn the led on
		if(readPA0()){
			PORT_OUTPUT_DATA_ADDR |= (1 << 12);
			continue;
		}
		// turn the led off
		PORT_OUTPUT_DATA_ADDR &= ~(1 << 12);
	}
}
