/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

// Interrupt configuration addresses
#define NVIC_ISER0 (*(uint32_t volatile*) 0xE000E100)		// Set-enable
#define NVIC_ICER0 (*(uint32_t volatile*) 0XE000E180)		// Clear-enable
#define NVIC_ISPR0 (*(uint32_t volatile*) 0XE000E200)		// Set pending
#define NVIC_ICPR0 (*(uint32_t volatile*) 0XE000E280)		// Clear pending
// Priority
#define NVIC_IPR_28 (*(uint32_t volatile*) 0xE000E41C)		// Priority Regs [28:31]

// Global interrupt positions
#define TIM2_INT_POS 28
#define I2C_1_INT_POS 31


void interrupt_setup(){
	// Set-pending
	NVIC_ISPR0 |= (1 << (TIM2_INT_POS % 32));				// TIM2 interrupt set as pending
	NVIC_ISPR0 |= (1 << (I2C_1_INT_POS % 32));				// 1C2_1 interrupt set as pending
	// Set enable
	NVIC_ISER0 |= (1 << (TIM2_INT_POS % 32));				// TIM2 interrupt enable
//	NVIC_ISER0 |= (1 << (I2C_1_INT_POS % 32));				// 1C2_1 interrupt enable

	// delay
//	for(uint16_t i = 0; i < 2400; i++);

}


void trigger_priority_configured_interrupt(){
	// Clear the priority field
	NVIC_IPR_28 &= ~(0xFF);
	// Set the priority of the TIM2
	NVIC_IPR_28 |= 0xA0;
	// Set the priority of the IC2_1
	NVIC_IPR_28 |= 0x20000000;

	// Trigger interrupt
	interrupt_setup();
}


int main(void)
{
//	interrupt_setup();
//
//	printf("Setting priorities\n");

	trigger_priority_configured_interrupt();

	// Clear pending
	NVIC_ICPR0 |= (1 << (TIM2_INT_POS % 32));				// TIM2 interrupt enable
	NVIC_ICPR0 |= (1 << (I2C_1_INT_POS % 32));				// 1C2_1 interrupt enable
	// Disable interrupts
	NVIC_ICER0 |= (1 << (TIM2_INT_POS % 32));				// TIM2 interrupt enable
	NVIC_ICER0 |= (1 << (I2C_1_INT_POS % 32));				// 1C2_1 interrupt enable

    /* Loop forever */
	for(;;);
}


// ISR's
void TIM2_IRQHandler(){
	NVIC_ISER0 |= (1 << (I2C_1_INT_POS % 32));
	printf("In TIM2 interrupt\n");
}


void I2C1_EV_IRQHandler(){
	printf("In IC2_1 interrupt\n");
}

